ALTER TABLE public.available
  ALTER COLUMN jhi_begin TYPE TIMESTAMP(0) WITHOUT TIME ZONE;
  ALTER COLUMN jhi_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE;

ALTER TABLE public.appointment
  ALTER COLUMN jhi_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE;
